/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import javax.swing.*;

/**
 *
 * @author HP USER
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        playerButton = new javax.swing.JButton();
        coachButton = new javax.swing.JButton();
        managerButton = new javax.swing.JButton();
        fanButtom = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcome");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 0));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/football/football.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 350, 385);

        playerButton.setBackground(new java.awt.Color(255, 153, 0));
        playerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playerButton.setForeground(new java.awt.Color(0, 51, 153));
        playerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/football/fbbbbbbbbb.png"))); // NOI18N
        playerButton.setText("player");
        playerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playerButtonMouseClicked(evt);
            }
        });
        playerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playerButton);
        playerButton.setBounds(440, 150, 410, 100);

        coachButton.setBackground(new java.awt.Color(255, 153, 0));
        coachButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        coachButton.setForeground(new java.awt.Color(0, 102, 153));
        coachButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/football/coaach11.png"))); // NOI18N
        coachButton.setText("coach");
        coachButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coachButtonMouseClicked(evt);
            }
        });
        coachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coachButtonActionPerformed(evt);
            }
        });
        jPanel1.add(coachButton);
        coachButton.setBounds(440, 260, 410, 90);

        managerButton.setBackground(new java.awt.Color(255, 153, 0));
        managerButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        managerButton.setForeground(new java.awt.Color(0, 102, 204));
        managerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/football/mama.png"))); // NOI18N
        managerButton.setText("manager");
        managerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managerButtonMouseClicked(evt);
            }
        });
        jPanel1.add(managerButton);
        managerButton.setBounds(440, 360, 410, 90);

        fanButtom.setBackground(new java.awt.Color(255, 153, 0));
        fanButtom.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fanButtom.setForeground(new java.awt.Color(0, 102, 204));
        fanButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/football/fan (1)1.png"))); // NOI18N
        fanButtom.setText("others/fans");
        fanButtom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fanButtomMouseClicked(evt);
            }
        });
        jPanel1.add(fanButtom);
        fanButtom.setBounds(440, 460, 410, 90);

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("football players tournament managenent system");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(350, 0, 622, 100);

        jLabel3.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("welcome!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(24, 430, 300, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 973, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(973, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void playerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playerButtonActionPerformed

    private void playerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playerButtonMouseClicked
     welcome pl= new welcome();
     pl.setVisible(true);
     pl.setLocationRelativeTo(null);
     pl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
     
     
    }//GEN-LAST:event_playerButtonMouseClicked

    private void coachButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coachButtonMouseClicked
      
        welcomeCoach cl=new welcomeCoach();
        cl.setVisible(true);
        
        cl.setLocationRelativeTo(null);
        cl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   
    }//GEN-LAST:event_coachButtonMouseClicked

    private void managerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managerButtonMouseClicked
       welcomCoach c=new welcomCoach();
        c.setVisible(true);
        
        c.setLocationRelativeTo(null);
        c.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_managerButtonMouseClicked

    private void fanButtomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fanButtomMouseClicked
       coachLogin cl=new coachLogin();
        cl.setVisible(true);
        
        cl.setLocationRelativeTo(null);
        cl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_fanButtomMouseClicked

    private void coachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coachButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coachButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coachButton;
    private javax.swing.JButton fanButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton managerButton;
    private javax.swing.JButton playerButton;
    // End of variables declaration//GEN-END:variables
}
